import { QuizProvider } from "../context/QuizContext";
import {  Geist_Mono } from "next/font/google";
import "../globals.css";


const geistMono = Geist_Mono({ subsets: ["latin"] });

export const metadata = {
  title: "Quiz Flow",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    
  
        <QuizProvider>
            {children}
        </QuizProvider>
    
  );
}