import { QuizProvider } from "./context/QuizContext";
import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar"; 



export const metadata = {
  title: "Quiz Flow",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-gray-200 text-[#2b275d]">
        <QuizProvider>
          <Navbar /> 
          {children}
        </QuizProvider>
      </body>
    </html>
  );
}