import { QuizProvider } from "./context/QuizContext";
import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar"; // Import the Navbar component

const poppins = Poppins({
  weight: ["400", "600", "700"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Quiz Flow",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-indigo-900">
        <QuizProvider>
          <Navbar /> {/* Add the Navbar here */}
          {children}
        </QuizProvider>
      </body>
    </html>
  );
}